services:
  - type: web
    name: krishna-enterprises-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FIREBASE_PROJECT_ID
        value: krishna-enterprises-77254
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FRONTEND_URL
        sync: false
